all:
	@(cd publish; make)
	@(cd subscriber; make)
	@(cd sub_file_writer; make)
#	@(cd redis_server; make)

clean:
	@(cd publish; make clean)
	@(cd subscriber; make clean)
	@(cd sub_file_writer; make clean)
#	@(cd redis_server; make)
