debug/acl_debug_malloc.o debug/acl_debug_malloc.inc : src/stdlib/debug/acl_debug_malloc.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/thread/acl_thread.h \
 include/thread/acl_pthread.h include/thread/acl_pthread_rwlock.h \
 include/thread/acl_pthread.h include/thread/acl_pthread_pool.h \
 include/thread/acl_sem.h include/stdlib/acl_mem_hook.h \
 include/stdlib/acl_define.h include/stdlib/acl_debug_malloc.h \
 src/stdlib/debug/htable.h
