debug/acl_pthread_rwlock.o debug/acl_pthread_rwlock.inc : src/thread/acl_pthread_rwlock.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_mymalloc.h \
 include/stdlib/acl_define.h include/stdlib/acl_malloc.h \
 include/thread/acl_pthread.h include/thread/acl_pthread_rwlock.h
