debug/acl_base64.o debug/acl_base64.inc : src/code/acl_base64.c StdAfx.h include/stdlib/acl_define.h \
 include/stdlib/acl_define_win32.h include/stdlib/acl_define_unix.h \
 include/stdlib/acl_define_linux.h include/stdlib/acl_define_sunx86.h \
 include/stdlib/acl_define_bsd.h include/stdlib/acl_define_macosx.h \
 include/stdlib/acl_mymalloc.h include/stdlib/acl_define.h \
 include/stdlib/acl_malloc.h include/code/acl_base64.h
