debug/acl_username.o debug/acl_username.inc : src/stdlib/sys/unix/acl_username.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/unix/acl_username.h \
 include/stdlib/unix/../acl_define.h
