debug/acl_mystring.o debug/acl_mystring.inc : src/stdlib/string/acl_mystring.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_mymalloc.h \
 include/stdlib/acl_define.h include/stdlib/acl_malloc.h \
 include/stdlib/acl_vsprintf.h include/stdlib/acl_mystring.h
