debug/acl_test_cfg_general.o debug/acl_test_cfg_general.inc : src/unit_test/acl_test_cfg_general.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_loadcfg.h \
 include/stdlib/acl_define.h include/stdlib/acl_array.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_array.h \
 include/stdlib/acl_mystring.h include/unit_test/acl_unit_test.h \
 include/unit_test/acl_test_struct.h include/unit_test/acl_test_global.h \
 include/unit_test/acl_test_var.h include/unit_test/acl_test_macro.h
