debug/acl_gbcode.o debug/acl_gbcode.inc : src/code/acl_gbcode.c StdAfx.h include/stdlib/acl_define.h \
 include/stdlib/acl_define_win32.h include/stdlib/acl_define_unix.h \
 include/stdlib/acl_define_linux.h include/stdlib/acl_define_sunx86.h \
 include/stdlib/acl_define_bsd.h include/stdlib/acl_define_macosx.h \
 include/stdlib/acl_mymalloc.h include/stdlib/acl_define.h \
 include/stdlib/acl_malloc.h include/code/acl_gbcode.h \
 src/code/gb_jt2ft.h src/code/gb_ft2jt.h
