debug/acl_argv_split.o debug/acl_argv_split.inc : src/stdlib/common/acl_argv_split.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_mymalloc.h \
 include/stdlib/acl_define.h include/stdlib/acl_malloc.h \
 include/stdlib/acl_argv.h include/stdlib/acl_slice.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_mystring.h
