debug/acl_test_token.o debug/acl_test_token.inc : src/unit_test/acl_test_token.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/unit_test/acl_unit_test.h \
 include/unit_test/acl_test_struct.h include/stdlib/acl_array.h \
 include/stdlib/acl_define.h include/stdlib/acl_iterator.h \
 include/unit_test/acl_test_global.h include/stdlib/acl_loadcfg.h \
 include/stdlib/acl_array.h include/unit_test/acl_test_var.h \
 include/unit_test/acl_test_macro.h
