debug/acl_mem_slice.o debug/acl_mem_slice.inc : src/stdlib/memory/acl_mem_slice.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/init/acl_init.h \
 include/stdlib/acl_mem_hook.h include/stdlib/acl_define.h \
 include/stdlib/acl_malloc.h include/stdlib/acl_slice.h \
 include/stdlib/acl_mem_slice.h include/stdlib/acl_meter_time.h \
 src/stdlib/memory/../../private/private_array.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_array.h \
 include/stdlib/acl_iterator.h src/stdlib/memory/malloc_vars.h \
 src/stdlib/memory/../../private/thread.h include/thread/acl_pthread.h \
 include/stdlib/acl_msg.h include/stdlib/acl_vstream.h \
 include/stdlib/acl_array.h include/stdlib/acl_htable.h \
 include/thread/acl_thread.h include/thread/acl_pthread.h \
 include/thread/acl_pthread_rwlock.h include/thread/acl_pthread_pool.h \
 include/thread/acl_sem.h include/stdlib/acl_hash.h \
 include/stdlib/acl_slice.h include/stdlib/acl_vstring.h \
 include/stdlib/acl_vbuf.h include/stdlib/acl_dbuf_pool.h
