debug/events_dog.o debug/events_dog.inc : src/event/events_dog.c StdAfx.h include/stdlib/acl_define.h \
 include/stdlib/acl_define_win32.h include/stdlib/acl_define_unix.h \
 include/stdlib/acl_define_linux.h include/stdlib/acl_define_sunx86.h \
 include/stdlib/acl_define_bsd.h include/stdlib/acl_define_macosx.h \
 include/stdlib/acl_mymalloc.h include/stdlib/acl_define.h \
 include/stdlib/acl_malloc.h include/stdlib/acl_msg.h \
 include/stdlib/acl_vstream.h include/stdlib/acl_array.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_htable.h \
 include/thread/acl_thread.h include/thread/acl_pthread.h \
 include/thread/acl_pthread_rwlock.h include/thread/acl_pthread.h \
 include/thread/acl_pthread_pool.h include/thread/acl_sem.h \
 include/stdlib/acl_hash.h include/stdlib/acl_slice.h \
 include/stdlib/acl_vstring.h include/stdlib/acl_vbuf.h \
 include/stdlib/acl_dbuf_pool.h include/net/acl_vstream_net.h \
 include/stdlib/acl_vstream.h include/stdlib/acl_iostuff.h \
 include/event/acl_events.h include/event/acl_timer.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_ring.h \
 src/event/events_dog.h
