debug/master_pathname.o debug/master_pathname.inc : src/master/framework/master_pathname.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_stringops.h \
 include/stdlib/acl_define.h src/master/framework/master_pathname.h
