debug/master_service.o debug/master_service.inc : src/master/framework/master_service.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_msg.h \
 include/stdlib/acl_define.h include/stdlib/acl_vstream.h \
 include/stdlib/acl_array.h include/stdlib/acl_iterator.h \
 include/stdlib/acl_htable.h include/thread/acl_thread.h \
 include/thread/acl_pthread.h include/thread/acl_pthread_rwlock.h \
 include/thread/acl_pthread.h include/thread/acl_pthread_pool.h \
 include/thread/acl_sem.h include/stdlib/acl_hash.h \
 include/stdlib/acl_slice.h include/stdlib/acl_vstring.h \
 include/stdlib/acl_vbuf.h include/stdlib/acl_dbuf_pool.h \
 include/event/acl_events.h include/stdlib/acl_vstream.h \
 include/event/acl_timer.h include/stdlib/acl_iterator.h \
 include/stdlib/acl_ring.h src/master/framework/../master_params.h \
 include/master/acl_master_type.h include/stdlib/acl_xinetd_cfg.h \
 include/master/acl_master_conf.h src/master/framework/master.h \
 include/stdlib/acl_array.h include/net/acl_netdb.h
