debug/mem_pool.o debug/mem_pool.inc : src/stdlib/memory/mem_pool.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_allocator.h \
 include/stdlib/acl_define.h src/stdlib/memory/allocator.h \
 include/stdlib/acl_stack.h include/stdlib/acl_iterator.h
