debug/private_fifo.o debug/private_fifo.inc : src/private/private_fifo.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h src/private/private_fifo.h \
 include/stdlib/acl_fifo.h include/stdlib/acl_define.h \
 include/stdlib/acl_slice.h include/stdlib/acl_iterator.h \
 include/stdlib/acl_malloc.h
