debug/private_array.o debug/private_array.inc : src/private/private_array.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h src/private/private_array.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_array.h \
 include/stdlib/acl_define.h include/stdlib/acl_iterator.h
