debug/squid_allocator_tools.o debug/squid_allocator_tools.inc : src/stdlib/memory/squid_allocator_tools.c \
 StdAfx.h include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h src/stdlib/memory/squid_allocator.h \
 include/stdlib/acl_allocator.h include/stdlib/acl_define.h \
 src/stdlib/memory/allocator.h include/stdlib/acl_stack.h \
 include/stdlib/acl_iterator.h
