debug/strcasecmp.o debug/strcasecmp.inc : src/stdlib/string/strcasecmp.c StdAfx.h \
 include/stdlib/acl_define.h include/stdlib/acl_define_win32.h \
 include/stdlib/acl_define_unix.h include/stdlib/acl_define_linux.h \
 include/stdlib/acl_define_sunx86.h include/stdlib/acl_define_bsd.h \
 include/stdlib/acl_define_macosx.h include/stdlib/acl_mystring.h \
 include/stdlib/acl_define.h src/stdlib/string/../charmap.h
