debug/zdb_dat_iter.o debug/zdb_dat_iter.inc : src/db/zdb/zdb_dat_iter.c StdAfx.h \
 include/init/acl_init.h include/stdlib/acl_define.h \
 include/stdlib/acl_define_win32.h include/stdlib/acl_define_unix.h \
 include/stdlib/acl_define_linux.h include/stdlib/acl_define_sunx86.h \
 include/stdlib/acl_define_bsd.h include/stdlib/acl_define_macosx.h \
 include/stdlib/acl_msg.h include/stdlib/acl_define.h \
 include/stdlib/acl_vstream.h include/stdlib/acl_array.h \
 include/stdlib/acl_iterator.h include/stdlib/acl_htable.h \
 include/thread/acl_thread.h include/thread/acl_pthread.h \
 include/thread/acl_pthread_rwlock.h include/thread/acl_pthread.h \
 include/thread/acl_pthread_pool.h include/thread/acl_sem.h \
 include/stdlib/acl_hash.h include/stdlib/acl_slice.h \
 include/stdlib/acl_vstring.h include/stdlib/acl_vbuf.h \
 include/stdlib/acl_dbuf_pool.h include/stdlib/acl_mymalloc.h \
 include/stdlib/acl_malloc.h include/db/zdb.h \
 include/stdlib/acl_vstring.h include/stdlib/acl_fhandle.h \
 include/stdlib/acl_ring.h src/db/zdb/zdb_private.h
