CC		= g++
CFLAGS		= -g -c -Wall
LDFLAGS		= 
SOURCES		= tcpstream.cpp tcpconnector.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)

all: $(SOURCES) 

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) 

